### ISSUE TITLE
Don't receive notifications when profile handle with uppercase

### ISSUE THREAD

**Issue by emilienbidet** [EnixCoda/github-code-review-notifier#21]
My last account handle was EmilienBidet.

I tried the GitHub Code Review Notifier after link my account all my colleagues can receive their pings except me.

Then I tried to change my account handle by emilienbidet and it cames back :)

**Comment by EnixCoda** [comment]
Hi @emilienbidet 
What is `account handle` ? Is it your GitHub account name, or Slack name?

**Comment by emilienbidet** [comment]
Hello !
It's the github account handle. 

Before it was :
https://github.com/EmilienBidet
And it didn't work

Now it is :
https://github.com/emilienbidet
And it works well

**Comment by EnixCoda** [comment]
Thank you for submitting this issue so that I could find out that the service was actually down due to a build error since 10 days ago 😅 Have no idea why your colleagues could use it at that time.

Now the build error has been fixed. I tested with my own account (mine also have uppercase characters) and most features work well.

You can revert your GitHub account to try again if you'd like. 😁
